"""
DAG 1 of 4 — MSSQL Migration: Ingest to Bronze
================================================
SOURCE  : S3 bucket (DMS full-load Parquet files)
          RAW_MSSQL.RAW_DMS_VARIANT (Snowflake VARIANT table)
TARGET  : MSSQL_MIGRATION_LAB.BRONZE.*  (15 typed tables)

What it does
------------
Step 1  copy_raw_from_s3     COPY INTO RAW_MSSQL.RAW_DMS_VARIANT from S3 stage
Step 2  check_raw_count      Assert > 0 rows landed in RAW (fail-fast gate)
Step 3  merge_bronze_stress  MERGE → BRONZE.CUSTOMERS / PRODUCTS / CATEGORIES /
                                     ORDERS / ORDER_ITEMS
Step 4  merge_bronze_erp     MERGE → BRONZE.ERP_DEPARTMENTS / ERP_EMPLOYEES /
                                     ERP_PAYROLL_RUNS / ERP_PAYROLL_LINES
Step 5  merge_bronze_crm     MERGE → BRONZE.CRM_ACCOUNTS / CRM_CONTACTS /
                                     CRM_OPPORTUNITIES
Step 6  merge_bronze_inv     MERGE → BRONZE.INV_WAREHOUSES / INV_SKU /
                                     INV_STOCK_MOVEMENTS
Step 7  report_bronze_counts SELECT COUNT(*) for each Bronze table

Schedule: @daily (runs once per day after DMS dump lands in S3)
Trigger:  Can also be triggered manually or via S3 event sensor
"""
from __future__ import annotations
import os
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator

CONN   = "snowflake_default"
DB     = "MSSQL_MIGRATION_LAB"
RAW    = "RAW_MSSQL"
BRZ    = "BRONZE"
WH     = "WH_MSSQL_MIGRATION"
ROLE   = "ACCOUNTADMIN"

ARGS = {"owner": "data-platform", "retries": 1, "retry_delay": timedelta(minutes=5)}

# ── SQL blocks ────────────────────────────────────────────────────────────────

COPY_RAW = f"""
COPY INTO {DB}.{RAW}.RAW_DMS_VARIANT(V)
FROM @{DB}.{RAW}.STG_DMS_MSSQL
FILE_FORMAT = (TYPE = PARQUET)
FORCE = FALSE;
"""

CHECK_RAW = f"SELECT COUNT(*) AS raw_rows FROM {DB}.{RAW}.RAW_DMS_VARIANT;"

MERGE_STRESS = f"""
USE DATABASE {DB}; USE WAREHOUSE {WH};

MERGE INTO {BRZ}.CUSTOMERS tgt
USING (SELECT DISTINCT
    v:CustomerId::NUMBER AS CUSTOMER_ID, v:CustomerCode::VARCHAR(20) AS CUSTOMER_CODE,
    v:FullName::VARCHAR(200) AS FULL_NAME, v:Email::VARCHAR(320) AS EMAIL,
    v:Country::VARCHAR(100) AS COUNTRY, v:CreatedAt::TIMESTAMP_NTZ AS CREATED_AT,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT,
    'SnowConvertStressDB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:CustomerId IS NOT NULL) src
ON tgt.CUSTOMER_ID=src.CUSTOMER_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    FULL_NAME=src.FULL_NAME, EMAIL=src.EMAIL, COUNTRY=src.COUNTRY, _LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT
    (CUSTOMER_ID,CUSTOMER_CODE,FULL_NAME,EMAIL,COUNTRY,CREATED_AT,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.CUSTOMER_ID,src.CUSTOMER_CODE,src.FULL_NAME,src.EMAIL,src.COUNTRY,
           src.CREATED_AT,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.CATEGORIES tgt
USING (SELECT DISTINCT v:CategoryId::NUMBER AS CATEGORY_ID,
    v:CategoryName::VARCHAR(100) AS CATEGORY_NAME, v:Description::VARCHAR(500) AS DESCRIPTION,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'SnowConvertStressDB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:CategoryId IS NOT NULL AND v:CategoryName IS NOT NULL) src
ON tgt.CATEGORY_ID=src.CATEGORY_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.CATEGORY_ID,src.CATEGORY_NAME,src.DESCRIPTION,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.PRODUCTS tgt
USING (SELECT DISTINCT v:ProductId::NUMBER AS PRODUCT_ID, v:CategoryId::NUMBER AS CATEGORY_ID,
    v:SKU::VARCHAR(50) AS SKU, v:ProductName::VARCHAR(200) AS PRODUCT_NAME,
    v:ListPrice::NUMBER(18,4) AS LIST_PRICE, v:IsActive::BOOLEAN AS IS_ACTIVE,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'SnowConvertStressDB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:ProductId IS NOT NULL) src
ON tgt.PRODUCT_ID=src.PRODUCT_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    LIST_PRICE=src.LIST_PRICE,IS_ACTIVE=src.IS_ACTIVE,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT
    (PRODUCT_ID,CATEGORY_ID,SKU,PRODUCT_NAME,LIST_PRICE,IS_ACTIVE,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.PRODUCT_ID,src.CATEGORY_ID,src.SKU,src.PRODUCT_NAME,src.LIST_PRICE,
           src.IS_ACTIVE,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.ORDERS tgt
USING (SELECT DISTINCT v:OrderId::NUMBER AS ORDER_ID, v:CustomerId::NUMBER AS CUSTOMER_ID,
    v:OrderDate::DATE AS ORDER_DATE, v:Status::VARCHAR(30) AS STATUS,
    v:TotalAmount::NUMBER(18,4) AS TOTAL_AMOUNT, v:Notes::VARCHAR(500) AS NOTES,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'SnowConvertStressDB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:OrderId IS NOT NULL) src
ON tgt.ORDER_ID=src.ORDER_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    STATUS=src.STATUS,TOTAL_AMOUNT=src.TOTAL_AMOUNT,NOTES=src.NOTES,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT
    (ORDER_ID,CUSTOMER_ID,ORDER_DATE,STATUS,TOTAL_AMOUNT,NOTES,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.ORDER_ID,src.CUSTOMER_ID,src.ORDER_DATE,src.STATUS,src.TOTAL_AMOUNT,
           src.NOTES,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.ORDER_ITEMS tgt
USING (SELECT DISTINCT v:OrderItemId::NUMBER AS ORDER_ITEM_ID, v:OrderId::NUMBER AS ORDER_ID,
    v:ProductId::NUMBER AS PRODUCT_ID, v:Quantity::NUMBER AS QUANTITY,
    v:UnitPrice::NUMBER(18,4) AS UNIT_PRICE,
    COALESCE(v:LineTotal::NUMBER(18,4), v:Quantity::NUMBER*v:UnitPrice::NUMBER(18,4)) AS LINE_TOTAL,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'SnowConvertStressDB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:OrderItemId IS NOT NULL) src
ON tgt.ORDER_ITEM_ID=src.ORDER_ITEM_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT
    (ORDER_ITEM_ID,ORDER_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,LINE_TOTAL,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.ORDER_ITEM_ID,src.ORDER_ID,src.PRODUCT_ID,src.QUANTITY,src.UNIT_PRICE,
           src.LINE_TOTAL,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);
"""

MERGE_ERP = f"""
USE DATABASE {DB}; USE WAREHOUSE {WH};

MERGE INTO {BRZ}.ERP_DEPARTMENTS tgt
USING (SELECT DISTINCT v:DeptId::NUMBER AS DEPT_ID, v:DeptCode::VARCHAR(20) AS DEPT_CODE,
    v:DeptName::VARCHAR(120) AS DEPT_NAME, v:BudgetUsd::NUMBER(18,2) AS BUDGET_USD,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabERP_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:DeptId IS NOT NULL) src
ON tgt.DEPT_ID=src.DEPT_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (DEPT_ID,DEPT_CODE,DEPT_NAME,BUDGET_USD,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.DEPT_ID,src.DEPT_CODE,src.DEPT_NAME,src.BUDGET_USD,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.ERP_EMPLOYEES tgt
USING (SELECT DISTINCT v:EmployeeId::NUMBER AS EMP_ID, v:DeptId::NUMBER AS DEPT_ID,
    v:EmpCode::VARCHAR(20) AS EMP_CODE, v:FullName::VARCHAR(200) AS FULL_NAME,
    v:HireDate::DATE AS HIRE_DATE, v:Salary::NUMBER(18,4) AS SALARY,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabERP_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:EmployeeId IS NOT NULL) src
ON tgt.EMP_ID=src.EMP_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    SALARY=src.SALARY,DEPT_ID=src.DEPT_ID,FULL_NAME=src.FULL_NAME,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT (EMP_ID,DEPT_ID,EMP_CODE,FULL_NAME,HIRE_DATE,SALARY,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.EMP_ID,src.DEPT_ID,src.EMP_CODE,src.FULL_NAME,src.HIRE_DATE,
           src.SALARY,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.ERP_PAYROLL_RUNS tgt
USING (SELECT DISTINCT v:RunId::NUMBER AS RUN_ID, v:RunMonth::VARCHAR(7) AS RUN_MONTH,
    v:Status::VARCHAR(20) AS STATUS, v:CreatedAt::TIMESTAMP_NTZ AS CREATED_AT,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabERP_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:RunId IS NOT NULL) src
ON tgt.RUN_ID=src.RUN_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED THEN UPDATE SET STATUS=src.STATUS,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT (RUN_ID,RUN_MONTH,STATUS,CREATED_AT,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.RUN_ID,src.RUN_MONTH,src.STATUS,src.CREATED_AT,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.ERP_PAYROLL_LINES tgt
USING (SELECT DISTINCT v:LineId::NUMBER AS LINE_ID, v:RunId::NUMBER AS RUN_ID,
    v:EmployeeId::NUMBER AS EMP_ID, v:GrossPay::NUMBER(18,4) AS GROSS_PAY,
    COALESCE(v:NetPay::NUMBER(18,4), v:GrossPay::NUMBER(18,4)*0.92) AS NET_PAY,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabERP_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:LineId IS NOT NULL) src
ON tgt.LINE_ID=src.LINE_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (LINE_ID,RUN_ID,EMP_ID,GROSS_PAY,NET_PAY,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.LINE_ID,src.RUN_ID,src.EMP_ID,src.GROSS_PAY,src.NET_PAY,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);
"""

MERGE_CRM = f"""
USE DATABASE {DB}; USE WAREHOUSE {WH};

MERGE INTO {BRZ}.CRM_ACCOUNTS tgt
USING (SELECT DISTINCT v:AccountId::NUMBER AS ACCOUNT_ID,
    v:AccountCode::VARCHAR(30) AS ACCOUNT_CODE, v:Name::VARCHAR(200) AS NAME,
    v:Region::VARCHAR(50) AS REGION, v:CreatedAt::TIMESTAMP_NTZ AS CREATED_AT,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabCRM_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:AccountId IS NOT NULL) src
ON tgt.ACCOUNT_ID=src.ACCOUNT_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    NAME=src.NAME,REGION=src.REGION,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT (ACCOUNT_ID,ACCOUNT_CODE,NAME,REGION,CREATED_AT,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.ACCOUNT_ID,src.ACCOUNT_CODE,src.NAME,src.REGION,src.CREATED_AT,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.CRM_CONTACTS tgt
USING (SELECT DISTINCT v:ContactId::NUMBER AS CONTACT_ID, v:AccountId::NUMBER AS ACCOUNT_ID,
    v:Email::VARCHAR(320) AS EMAIL, v:FullName::VARCHAR(200) AS FULL_NAME,
    v:IsPrimary::BOOLEAN AS IS_PRIMARY,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabCRM_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:ContactId IS NOT NULL) src
ON tgt.CONTACT_ID=src.CONTACT_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (CONTACT_ID,ACCOUNT_ID,EMAIL,FULL_NAME,IS_PRIMARY,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.CONTACT_ID,src.ACCOUNT_ID,src.EMAIL,src.FULL_NAME,src.IS_PRIMARY,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.CRM_OPPORTUNITIES tgt
USING (SELECT DISTINCT v:OppId::NUMBER AS OPP_ID, v:AccountId::NUMBER AS ACCOUNT_ID,
    v:Title::VARCHAR(200) AS TITLE, v:Stage::VARCHAR(40) AS STAGE,
    v:AmountUsd::NUMBER(18,2) AS AMOUNT_USD, v:CloseDate::DATE AS CLOSE_DATE,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabCRM_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:OppId IS NOT NULL) src
ON tgt.OPP_ID=src.OPP_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    STAGE=src.STAGE,AMOUNT_USD=src.AMOUNT_USD,CLOSE_DATE=src.CLOSE_DATE,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT (OPP_ID,ACCOUNT_ID,TITLE,STAGE,AMOUNT_USD,CLOSE_DATE,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.OPP_ID,src.ACCOUNT_ID,src.TITLE,src.STAGE,src.AMOUNT_USD,src.CLOSE_DATE,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);
"""

MERGE_INV = f"""
USE DATABASE {DB}; USE WAREHOUSE {WH};

MERGE INTO {BRZ}.INV_WAREHOUSES tgt
USING (SELECT DISTINCT v:WhId::NUMBER AS WH_ID, v:WhCode::VARCHAR(20) AS WH_CODE,
    v:Location::VARCHAR(200) AS LOCATION,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabInventory_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:WhId IS NOT NULL) src
ON tgt.WH_ID=src.WH_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (WH_ID,WH_CODE,LOCATION,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.WH_ID,src.WH_CODE,src.LOCATION,src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.INV_SKU tgt
USING (SELECT DISTINCT v:SkuId::NUMBER AS SKU_ID, v:SkuCode::VARCHAR(40) AS SKU_CODE,
    v:Descr::VARCHAR(200) AS DESCR, v:UnitCost::NUMBER(18,4) AS UNIT_COST,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabInventory_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:SkuId IS NOT NULL) src
ON tgt.SKU_ID=src.SKU_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN MATCHED AND src._LOADED_AT>tgt._LOADED_AT THEN UPDATE SET
    DESCR=src.DESCR,UNIT_COST=src.UNIT_COST,_LOADED_AT=src._LOADED_AT
WHEN NOT MATCHED THEN INSERT (SKU_ID,SKU_CODE,DESCR,UNIT_COST,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.SKU_ID,src.SKU_CODE,src.DESCR,src.UNIT_COST,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);

MERGE INTO {BRZ}.INV_STOCK_MOVEMENTS tgt
USING (SELECT DISTINCT v:MovId::NUMBER AS MOV_ID, v:WhId::NUMBER AS WH_ID,
    v:SkuId::NUMBER AS SKU_ID, v:QtyChange::NUMBER AS QTY_CHANGE,
    v:Reason::VARCHAR(80) AS REASON, v:MovDate::TIMESTAMP_NTZ AS MOV_DATE,
    'I' AS _DMS_OPERATION, CURRENT_TIMESTAMP() AS _LOADED_AT, 'LabInventory_DB' AS _SOURCE_DB
    FROM {RAW}.RAW_DMS_VARIANT WHERE v:MovId IS NOT NULL) src
ON tgt.MOV_ID=src.MOV_ID AND tgt._SOURCE_DB=src._SOURCE_DB
WHEN NOT MATCHED THEN INSERT (MOV_ID,WH_ID,SKU_ID,QTY_CHANGE,REASON,MOV_DATE,_DMS_OPERATION,_LOADED_AT,_SOURCE_DB)
    VALUES(src.MOV_ID,src.WH_ID,src.SKU_ID,src.QTY_CHANGE,src.REASON,src.MOV_DATE,
           src._DMS_OPERATION,src._LOADED_AT,src._SOURCE_DB);
"""

REPORT = f"""
SELECT table_name, row_count FROM (
    SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count FROM {DB}.{BRZ}.CUSTOMERS UNION ALL
    SELECT 'PRODUCTS',  COUNT(*) FROM {DB}.{BRZ}.PRODUCTS  UNION ALL
    SELECT 'CATEGORIES',COUNT(*) FROM {DB}.{BRZ}.CATEGORIES UNION ALL
    SELECT 'ORDERS',    COUNT(*) FROM {DB}.{BRZ}.ORDERS     UNION ALL
    SELECT 'ORDER_ITEMS',COUNT(*) FROM {DB}.{BRZ}.ORDER_ITEMS UNION ALL
    SELECT 'ERP_EMPLOYEES',COUNT(*) FROM {DB}.{BRZ}.ERP_EMPLOYEES UNION ALL
    SELECT 'ERP_PAYROLL_LINES',COUNT(*) FROM {DB}.{BRZ}.ERP_PAYROLL_LINES UNION ALL
    SELECT 'CRM_ACCOUNTS',COUNT(*) FROM {DB}.{BRZ}.CRM_ACCOUNTS UNION ALL
    SELECT 'CRM_OPPORTUNITIES',COUNT(*) FROM {DB}.{BRZ}.CRM_OPPORTUNITIES UNION ALL
    SELECT 'INV_SKU',   COUNT(*) FROM {DB}.{BRZ}.INV_SKU UNION ALL
    SELECT 'INV_STOCK_MOVEMENTS',COUNT(*) FROM {DB}.{BRZ}.INV_STOCK_MOVEMENTS
) ORDER BY table_name;
"""

with DAG(
    dag_id="mssql_01_ingest_bronze",
    default_args=ARGS,
    start_date=datetime(2024, 1, 1),
    schedule_interval="@daily",
    catchup=False,
    tags=["mssql-migration", "bronze", "ingest"],
    doc_md=__doc__,
) as dag:

    copy_raw   = SnowflakeOperator(task_id="copy_raw_from_s3",    snowflake_conn_id=CONN, sql=COPY_RAW,      warehouse=WH, database=DB, role=ROLE)
    check_raw  = SnowflakeOperator(task_id="check_raw_count",     snowflake_conn_id=CONN, sql=CHECK_RAW,     warehouse=WH, database=DB)
    mrg_stress = SnowflakeOperator(task_id="merge_bronze_stress", snowflake_conn_id=CONN, sql=MERGE_STRESS,  warehouse=WH, database=DB, role=ROLE)
    mrg_erp    = SnowflakeOperator(task_id="merge_bronze_erp",    snowflake_conn_id=CONN, sql=MERGE_ERP,     warehouse=WH, database=DB, role=ROLE)
    mrg_crm    = SnowflakeOperator(task_id="merge_bronze_crm",    snowflake_conn_id=CONN, sql=MERGE_CRM,     warehouse=WH, database=DB, role=ROLE)
    mrg_inv    = SnowflakeOperator(task_id="merge_bronze_inv",    snowflake_conn_id=CONN, sql=MERGE_INV,     warehouse=WH, database=DB, role=ROLE)
    report     = SnowflakeOperator(task_id="report_bronze_counts",snowflake_conn_id=CONN, sql=REPORT,        warehouse=WH, database=DB)

    copy_raw >> check_raw >> [mrg_stress, mrg_erp, mrg_crm, mrg_inv] >> report
