-- ============================================================================
-- Snowflake University: Transient Tables Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE SCHEMA IF NOT EXISTS STAGING_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.PUBLIC;
USE DATABASE STAGING_DB;

CREATE OR REPLACE TRANSIENT TABLE STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT CLONE RAW_DB.PUBLIC.RAW_ORDERS;
SELECT COUNT(*), MAX(CREATED_AT) FROM STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT;

CREATE OR REPLACE TABLE SILVER_DB.PUBLIC.STG_ORDERS_PERMANENT AS
SELECT * FROM STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT;
SELECT COUNT(*), MAX(CREATED_AT) FROM SILVER_DB.PUBLIC.STG_ORDERS_PERMANENT;

SHOW TABLES LIKE 'STG_ORDERS%' IN SCHEMA STAGING_DB.PUBLIC;
SHOW TABLES LIKE 'STG_ORDERS%' IN SCHEMA SILVER_DB.PUBLIC;

CREATE OR REPLACE TEMPORARY TABLE STAGING_DB.PUBLIC.STG_ORDERS_CANCEL_SAMPLE AS
SELECT ORDER_ID FROM STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT SAMPLE (10000 ROWS);

UPDATE STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT t
SET ORDER_STATUS = 'cancelled'
FROM STAGING_DB.PUBLIC.STG_ORDERS_CANCEL_SAMPLE s
WHERE t.ORDER_ID = s.ORDER_ID;

SELECT COUNT(*) AS cancelled_now FROM STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT WHERE ORDER_STATUS = 'cancelled';
SELECT COUNT(*) AS cancelled_before_update FROM STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT BEFORE(STATEMENT => LAST_QUERY_ID()) WHERE ORDER_STATUS = 'cancelled';

EXECUTE IMMEDIATE $$
BEGIN
  CREATE OR REPLACE TABLE SILVER_DB.PUBLIC.STG_ORDERS_CLONED_TO_PERM CLONE STAGING_DB.PUBLIC.STG_ORDERS_TRANSIENT;
  RETURN 'unexpected_success';
EXCEPTION
  WHEN STATEMENT_ERROR THEN
    RETURN 'expected_failure: ' || SQLERRM;
END;
$$;
SELECT COUNT(*), MAX(CREATED_AT) FROM SILVER_DB.PUBLIC.STG_ORDERS_PERMANENT;

SELECT * FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
WHERE TABLE_NAME IN ('STG_ORDERS_TRANSIENT','STG_ORDERS_PERMANENT','STG_ORDERS_CLONED_TO_PERM')
ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME;

SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
