USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

INSERT INTO RAW_DB.PUBLIC.RAW_ORDERS
SELECT UUID_STRING(), UNIFORM(1, 500000, RANDOM()), UNIFORM(1, 200000, RANDOM()),
       ARRAY_CONSTRUCT('pending','shipped','delivered','cancelled')[UNIFORM(0,4,RANDOM())]::STRING,
       CURRENT_TIMESTAMP(), ARRAY_CONSTRUCT('NORTH','SOUTH','EAST','WEST','CENTRAL')[UNIFORM(0,5,RANDOM())]::STRING,
       ROUND(UNIFORM(100, 150000, RANDOM()) / 100, 2), UNIFORM(1, 5, RANDOM()), CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

CREATE OR REPLACE TEMPORARY TABLE RAW_DB.PUBLIC.ORDERS_CDC_SAMPLE AS
SELECT ORDER_ID FROM RAW_DB.PUBLIC.RAW_ORDERS SAMPLE (10000 ROWS);

UPDATE RAW_DB.PUBLIC.RAW_ORDERS t
SET ORDER_STATUS = 'cancelled', CREATED_AT = CURRENT_TIMESTAMP()
FROM RAW_DB.PUBLIC.ORDERS_CDC_SAMPLE s
WHERE t.ORDER_ID = s.ORDER_ID;

SELECT COUNT(*) AS stream_backlog_rows FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
