-- ============================================================================
-- Snowflake University: Streams Consumption
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();
SET batch_ts = CURRENT_TIMESTAMP();

CREATE SCHEMA IF NOT EXISTS SILVER_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.PUBLIC;

CREATE TABLE IF NOT EXISTS SILVER_DB.PUBLIC.ORDERS_SILVER LIKE RAW_DB.PUBLIC.RAW_ORDERS;
CREATE TABLE IF NOT EXISTS AUDIT_DB.PUBLIC.ORDERS_AUDIT (
  CONSUMED_AT TIMESTAMP_NTZ,
  METADATA_ACTION STRING,
  METADATA_ISUPDATE BOOLEAN,
  METADATA_ROW_ID STRING,
  ORDER_ID STRING,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  ORDER_STATUS STRING,
  ORDER_DATE TIMESTAMP_NTZ,
  REGION STRING,
  AMOUNT NUMBER(10,2),
  QUANTITY NUMBER,
  CREATED_AT TIMESTAMP_NTZ
);

SELECT METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID, *
FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM
LIMIT 100;

INSERT INTO AUDIT_DB.PUBLIC.ORDERS_AUDIT
SELECT $batch_ts, METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID,
       ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CREATED_AT
FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;

MERGE INTO SILVER_DB.PUBLIC.ORDERS_SILVER t
USING (
  SELECT r.ORDER_ID, r.CUSTOMER_ID, r.PRODUCT_ID, r.ORDER_STATUS, r.ORDER_DATE, r.REGION, r.AMOUNT, r.QUANTITY, r.CREATED_AT
  FROM RAW_DB.PUBLIC.RAW_ORDERS r
  JOIN (
    SELECT DISTINCT ORDER_ID
    FROM AUDIT_DB.PUBLIC.ORDERS_AUDIT
    WHERE CONSUMED_AT = $batch_ts
      AND METADATA_ACTION = 'INSERT'
  ) changed_orders
    ON r.ORDER_ID = changed_orders.ORDER_ID
) s
ON t.ORDER_ID = s.ORDER_ID
WHEN MATCHED THEN UPDATE SET
  CUSTOMER_ID = s.CUSTOMER_ID,
  PRODUCT_ID = s.PRODUCT_ID,
  ORDER_STATUS = s.ORDER_STATUS,
  ORDER_DATE = s.ORDER_DATE,
  REGION = s.REGION,
  AMOUNT = s.AMOUNT,
  QUANTITY = s.QUANTITY,
  CREATED_AT = s.CREATED_AT
WHEN NOT MATCHED THEN INSERT (ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CREATED_AT)
VALUES (s.ORDER_ID, s.CUSTOMER_ID, s.PRODUCT_ID, s.ORDER_STATUS, s.ORDER_DATE, s.REGION, s.AMOUNT, s.QUANTITY, s.CREATED_AT);

DELETE FROM SILVER_DB.PUBLIC.ORDERS_SILVER t
USING (
  SELECT d.ORDER_ID
  FROM AUDIT_DB.PUBLIC.ORDERS_AUDIT d
  WHERE d.CONSUMED_AT = $batch_ts
    AND d.METADATA_ACTION = 'DELETE'
    AND NOT EXISTS (
      SELECT 1
      FROM AUDIT_DB.PUBLIC.ORDERS_AUDIT i
      WHERE i.CONSUMED_AT = d.CONSUMED_AT
        AND i.ORDER_ID = d.ORDER_ID
        AND i.METADATA_ACTION = 'INSERT'
    )
) s
WHERE t.ORDER_ID = s.ORDER_ID;

SELECT COUNT(*) AS stream_rows_after_commit FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;
SELECT COUNT(*) AS audit_rows, MAX(CONSUMED_AT) AS last_consumed_at FROM AUDIT_DB.PUBLIC.ORDERS_AUDIT;
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
