-- ============================================================================
-- Snowflake University: Streams Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE SCHEMA IF NOT EXISTS RAW_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.PUBLIC;
USE DATABASE RAW_DB;

CREATE OR REPLACE STAGE RAW_DB.PUBLIC.RAW_STAGE DIRECTORY = (ENABLE = TRUE);
CREATE OR REPLACE VIEW RAW_DB.PUBLIC.V_ORDERS_ENRICHED AS
SELECT o.*, p.CATEGORY FROM RAW_DB.PUBLIC.RAW_ORDERS o JOIN RAW_DB.PUBLIC.RAW_PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID;

CREATE OR REPLACE STREAM RAW_DB.PUBLIC.ORDERS_CDC_STREAM ON TABLE RAW_DB.PUBLIC.RAW_ORDERS;
CREATE OR REPLACE STREAM RAW_DB.PUBLIC.EVENTS_APPEND_STREAM ON TABLE RAW_DB.PUBLIC.RAW_EVENTS APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW_DB.PUBLIC.ENRICHED_ORDERS_STREAM ON VIEW RAW_DB.PUBLIC.V_ORDERS_ENRICHED;
CREATE OR REPLACE STREAM RAW_DB.PUBLIC.STAGE_FILES_STREAM ON STAGE RAW_DB.PUBLIC.RAW_STAGE;

CREATE TABLE IF NOT EXISTS SILVER_DB.PUBLIC.ORDERS_SILVER LIKE RAW_DB.PUBLIC.RAW_ORDERS;
CREATE TABLE IF NOT EXISTS AUDIT_DB.PUBLIC.ORDERS_AUDIT (
  CONSUMED_AT TIMESTAMP_NTZ,
  METADATA_ACTION STRING,
  METADATA_ISUPDATE BOOLEAN,
  METADATA_ROW_ID STRING,
  ORDER_ID STRING,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  ORDER_STATUS STRING,
  ORDER_DATE TIMESTAMP_NTZ,
  REGION STRING,
  AMOUNT NUMBER(10,2),
  QUANTITY NUMBER,
  CREATED_AT TIMESTAMP_NTZ
);
SELECT COUNT(*), MAX(CREATED_AT) FROM SILVER_DB.PUBLIC.ORDERS_SILVER;
SELECT COUNT(*), MAX(CONSUMED_AT) FROM AUDIT_DB.PUBLIC.ORDERS_AUDIT;

SELECT METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID, * FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM LIMIT 100;

BEGIN;
  INSERT INTO AUDIT_DB.PUBLIC.ORDERS_AUDIT
  SELECT CURRENT_TIMESTAMP(), METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID,
         ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CREATED_AT
  FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;
ROLLBACK;

SELECT COUNT(*) AS stream_rows_after_rollback FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;
SHOW STREAMS IN SCHEMA RAW_DB.PUBLIC;
ALTER TABLE RAW_DB.PUBLIC.RAW_ORDERS SET DATA_RETENTION_TIME_IN_DAYS = 0;
SHOW STREAMS IN SCHEMA RAW_DB.PUBLIC;
ALTER TABLE RAW_DB.PUBLIC.RAW_ORDERS SET DATA_RETENTION_TIME_IN_DAYS = 1;
SHOW STREAMS IN SCHEMA RAW_DB.PUBLIC;
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
