-- ============================================================================
-- Snowflake University: Tasks Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE SCHEMA IF NOT EXISTS SILVER_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS AUDIT_DB.PUBLIC;
USE DATABASE AUDIT_DB;

CREATE OR REPLACE TABLE SILVER_DB.PUBLIC.ORDERS_SILVER_TASK AS
SELECT *, FALSE AS IS_DELETED FROM RAW_DB.PUBLIC.RAW_ORDERS WHERE 1=0;
SELECT COUNT(*), MAX(CREATED_AT) FROM SILVER_DB.PUBLIC.ORDERS_SILVER_TASK;

CREATE OR REPLACE TABLE GOLD_DB.PUBLIC.ORDERS_DAILY_AGG (REPORT_DATE DATE, REGION STRING, TOTAL_AMOUNT NUMBER(18,2), ORDER_COUNT NUMBER);
SELECT COUNT(*), MAX(REPORT_DATE) FROM GOLD_DB.PUBLIC.ORDERS_DAILY_AGG;

CREATE OR REPLACE TABLE AUDIT_DB.PUBLIC.PIPELINE_RUNS (RUN_TS TIMESTAMP_NTZ, STATUS STRING, DETAILS STRING);
CREATE OR REPLACE TABLE AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE (
  RUN_TS TIMESTAMP_NTZ,
  METADATA_ACTION STRING,
  METADATA_ISUPDATE BOOLEAN,
  METADATA_ROW_ID STRING,
  ORDER_ID STRING,
  CUSTOMER_ID NUMBER,
  PRODUCT_ID NUMBER,
  ORDER_STATUS STRING,
  ORDER_DATE TIMESTAMP_NTZ,
  REGION STRING,
  AMOUNT NUMBER(10,2),
  QUANTITY NUMBER,
  CREATED_AT TIMESTAMP_NTZ
);
SELECT COUNT(*), MAX(RUN_TS) FROM AUDIT_DB.PUBLIC.PIPELINE_RUNS;

CREATE OR REPLACE PROCEDURE AUDIT_DB.PUBLIC.VALIDATE_STREAM_HAS_ROWS()
RETURNS STRING LANGUAGE SQL AS $$
DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO :v_count FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;
  RETURN 'rows=' || v_count;
END;
$$;

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.ROOT_TASK_INGEST
  SCHEDULE = 'USING CRON 0 * * * * UTC'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AS CALL AUDIT_DB.PUBLIC.VALIDATE_STREAM_HAS_ROWS();

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.TASK_CONSUME_STREAM
  AFTER AUDIT_DB.PUBLIC.ROOT_TASK_INGEST
  WHEN SYSTEM$STREAM_HAS_DATA('RAW_DB.PUBLIC.ORDERS_CDC_STREAM')
AS
  INSERT INTO AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE
  SELECT CURRENT_TIMESTAMP(), METADATA$ACTION, METADATA$ISUPDATE, METADATA$ROW_ID,
         ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CREATED_AT
  FROM RAW_DB.PUBLIC.ORDERS_CDC_STREAM;

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_SILVER
  AFTER AUDIT_DB.PUBLIC.TASK_CONSUME_STREAM
AS
  MERGE INTO SILVER_DB.PUBLIC.ORDERS_SILVER_TASK t
  USING (
    SELECT r.ORDER_ID, r.CUSTOMER_ID, r.PRODUCT_ID, r.ORDER_STATUS, r.ORDER_DATE, r.REGION, r.AMOUNT, r.QUANTITY, r.CREATED_AT
    FROM RAW_DB.PUBLIC.RAW_ORDERS r
    JOIN (
      SELECT DISTINCT ORDER_ID
      FROM AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE
      WHERE RUN_TS = (SELECT MAX(RUN_TS) FROM AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE)
        AND METADATA_ACTION = 'INSERT'
    ) changed_orders
      ON r.ORDER_ID = changed_orders.ORDER_ID
  ) s
  ON t.ORDER_ID = s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = s.CUSTOMER_ID,
    PRODUCT_ID = s.PRODUCT_ID,
    ORDER_STATUS = s.ORDER_STATUS,
    ORDER_DATE = s.ORDER_DATE,
    REGION = s.REGION,
    AMOUNT = s.AMOUNT,
    QUANTITY = s.QUANTITY,
    CREATED_AT = s.CREATED_AT,
    IS_DELETED = FALSE
  WHEN NOT MATCHED THEN INSERT (ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CREATED_AT, IS_DELETED)
  VALUES (s.ORDER_ID, s.CUSTOMER_ID, s.PRODUCT_ID, s.ORDER_STATUS, s.ORDER_DATE, s.REGION, s.AMOUNT, s.QUANTITY, s.CREATED_AT, FALSE);

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_DELETES
  AFTER AUDIT_DB.PUBLIC.TASK_CONSUME_STREAM
AS
  MERGE INTO SILVER_DB.PUBLIC.ORDERS_SILVER_TASK t
  USING (
    SELECT d.ORDER_ID
    FROM AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE d
    WHERE d.RUN_TS = (SELECT MAX(RUN_TS) FROM AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE)
      AND d.METADATA_ACTION = 'DELETE'
      AND NOT EXISTS (
        SELECT 1
        FROM AUDIT_DB.PUBLIC.ORDERS_TASK_STAGE i
        WHERE i.RUN_TS = d.RUN_TS
          AND i.ORDER_ID = d.ORDER_ID
          AND i.METADATA_ACTION = 'INSERT'
      )
  ) s
  ON t.ORDER_ID = s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET IS_DELETED = TRUE;

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.TASK_REFRESH_GOLD_AGGREGATES
  AFTER AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_SILVER, AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_DELETES
AS
  INSERT OVERWRITE INTO GOLD_DB.PUBLIC.ORDERS_DAILY_AGG
  SELECT ORDER_DATE::DATE, REGION, SUM(AMOUNT), COUNT(*)
  FROM SILVER_DB.PUBLIC.ORDERS_SILVER_TASK
  WHERE COALESCE(IS_DELETED, FALSE) = FALSE
  GROUP BY 1,2;

CREATE OR REPLACE TASK AUDIT_DB.PUBLIC.TASK_NOTIFY_COMPLETE
  AFTER AUDIT_DB.PUBLIC.TASK_REFRESH_GOLD_AGGREGATES
AS
  INSERT INTO AUDIT_DB.PUBLIC.PIPELINE_RUNS
  SELECT CURRENT_TIMESTAMP(), 'success', SYSTEM$TASK_RUNTIME_INFO('CURRENT_TASK_GRAPH_ORIGINAL_SCHEDULED_TIMESTAMP');

ALTER TASK AUDIT_DB.PUBLIC.TASK_NOTIFY_COMPLETE RESUME;
ALTER TASK AUDIT_DB.PUBLIC.TASK_REFRESH_GOLD_AGGREGATES RESUME;
ALTER TASK AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_DELETES RESUME;
ALTER TASK AUDIT_DB.PUBLIC.TASK_LOAD_ORDERS_SILVER RESUME;
ALTER TASK AUDIT_DB.PUBLIC.TASK_CONSUME_STREAM RESUME;
ALTER TASK AUDIT_DB.PUBLIC.ROOT_TASK_INGEST RESUME;

SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
  SCHEDULED_TIME_RANGE_START => DATEADD('hour', -24, CURRENT_TIMESTAMP),
  RESULT_LIMIT => 100
));
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
