-- ============================================================================
-- Snowflake University: Dynamic Tables Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE DATABASE IF NOT EXISTS BRONZE_DB;
CREATE DATABASE IF NOT EXISTS SILVER_DB;
CREATE DATABASE IF NOT EXISTS GOLD_DB;
CREATE SCHEMA IF NOT EXISTS BRONZE_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS SILVER_DB.PUBLIC;
CREATE SCHEMA IF NOT EXISTS GOLD_DB.PUBLIC;
USE DATABASE GOLD_DB;

CREATE OR REPLACE DYNAMIC TABLE BRONZE_DB.PUBLIC.DT_ORDERS_BRONZE TARGET_LAG = '1 minute' WAREHOUSE = COMPUTE_WH AS
SELECT ORDER_ID, CUSTOMER_ID, PRODUCT_ID, ORDER_STATUS, ORDER_DATE, REGION, AMOUNT, QUANTITY, CURRENT_TIMESTAMP AS DBT_LOADED_AT
FROM RAW_DB.PUBLIC.RAW_ORDERS;
SELECT COUNT(*), MAX(DBT_LOADED_AT) FROM BRONZE_DB.PUBLIC.DT_ORDERS_BRONZE;

CREATE OR REPLACE DYNAMIC TABLE SILVER_DB.PUBLIC.DT_ORDERS_SILVER TARGET_LAG = '5 minutes' WAREHOUSE = COMPUTE_WH AS
SELECT o.ORDER_ID, o.CUSTOMER_ID, c.TIER AS CUSTOMER_TIER, o.PRODUCT_ID, p.CATEGORY, p.SUB_CATEGORY,
       o.ORDER_STATUS, o.ORDER_DATE, o.REGION, o.AMOUNT,
       o.AMOUNT - (p.COST_PRICE * o.QUANTITY) AS GROSS_PROFIT, o.QUANTITY
FROM BRONZE_DB.PUBLIC.DT_ORDERS_BRONZE o
JOIN RAW_DB.PUBLIC.RAW_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
JOIN RAW_DB.PUBLIC.RAW_PRODUCTS p ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.ORDER_STATUS != 'cancelled';
SELECT COUNT(*), MAX(ORDER_DATE) FROM SILVER_DB.PUBLIC.DT_ORDERS_SILVER;

CREATE OR REPLACE DYNAMIC TABLE GOLD_DB.PUBLIC.DT_DAILY_REVENUE TARGET_LAG = '10 minutes' WAREHOUSE = COMPUTE_WH AS
SELECT ORDER_DATE::DATE AS REPORT_DATE, REGION, CATEGORY, CUSTOMER_TIER,
       COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT, SUM(AMOUNT) AS TOTAL_REVENUE,
       SUM(GROSS_PROFIT) AS TOTAL_GROSS_PROFIT, AVG(AMOUNT) AS AVG_ORDER_VALUE
FROM SILVER_DB.PUBLIC.DT_ORDERS_SILVER
GROUP BY 1,2,3,4;
SELECT COUNT(*), MAX(REPORT_DATE) FROM GOLD_DB.PUBLIC.DT_DAILY_REVENUE;

SHOW DYNAMIC TABLES IN ACCOUNT;
ALTER DYNAMIC TABLE GOLD_DB.PUBLIC.DT_DAILY_REVENUE REFRESH;
SELECT * FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_GRAPH_HISTORY(NAME => 'DT_DAILY_REVENUE'));
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
