-- ============================================================================
-- Snowflake University: Materialized Views Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE SCHEMA IF NOT EXISTS GOLD_DB.PUBLIC;
USE DATABASE GOLD_DB;

CREATE OR REPLACE MATERIALIZED VIEW GOLD_DB.PUBLIC.MV_ORDERS_BY_REGION_DAY AS
SELECT ORDER_DATE::DATE AS REPORT_DATE, REGION, ORDER_STATUS, COUNT(*) AS ORDER_COUNT,
       SUM(AMOUNT) AS TOTAL_AMOUNT, MIN(AMOUNT) AS MIN_ORDER, MAX(AMOUNT) AS MAX_ORDER
FROM RAW_DB.PUBLIC.RAW_ORDERS
GROUP BY 1,2,3;
SELECT COUNT(*), MAX(REPORT_DATE) FROM GOLD_DB.PUBLIC.MV_ORDERS_BY_REGION_DAY;

CREATE OR REPLACE MATERIALIZED VIEW GOLD_DB.PUBLIC.MV_HIGH_VALUE_ORDERS AS
SELECT * FROM RAW_DB.PUBLIC.RAW_ORDERS WHERE AMOUNT > 500 AND ORDER_STATUS = 'delivered';
SELECT COUNT(*), MAX(CREATED_AT) FROM GOLD_DB.PUBLIC.MV_HIGH_VALUE_ORDERS;

CREATE OR REPLACE MATERIALIZED VIEW GOLD_DB.PUBLIC.MV_RECENT_ORDERS CLUSTER BY (ORDER_DATE::DATE) AS
SELECT * FROM RAW_DB.PUBLIC.RAW_ORDERS WHERE ORDER_DATE >= '2024-01-01'::TIMESTAMP_NTZ;
SELECT COUNT(*), MAX(CREATED_AT) FROM GOLD_DB.PUBLIC.MV_RECENT_ORDERS;

CREATE OR REPLACE SECURE MATERIALIZED VIEW GOLD_DB.PUBLIC.MV_REGION_SUMMARY AS
SELECT REGION, COUNT(*) AS CNT, SUM(AMOUNT) AS TOTAL FROM RAW_DB.PUBLIC.RAW_ORDERS GROUP BY REGION;
SELECT COUNT(*), MAX(TOTAL) FROM GOLD_DB.PUBLIC.MV_REGION_SUMMARY;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;
SELECT REGION, SUM(AMOUNT) FROM RAW_DB.PUBLIC.RAW_ORDERS GROUP BY REGION;
SELECT * FROM GOLD_DB.PUBLIC.MV_ORDERS_BY_REGION_DAY WHERE REPORT_DATE = CURRENT_DATE;
SELECT query_id, bytes_scanned, rows_produced, execution_time FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION()) ORDER BY start_time DESC LIMIT 2;
SHOW MATERIALIZED VIEWS IN SCHEMA GOLD_DB.PUBLIC;
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
