USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();

CREATE OR REPLACE TEMPORARY TABLE RAW_DB.PUBLIC.PRODUCT_SNAPSHOT_SAMPLE AS
SELECT PRODUCT_ID FROM RAW_DB.PUBLIC.RAW_PRODUCTS SAMPLE (10000 ROWS);

UPDATE RAW_DB.PUBLIC.RAW_PRODUCTS t
SET UNIT_PRICE = ROUND(UNIT_PRICE * 1.10, 2), UPDATED_AT = CURRENT_TIMESTAMP()
FROM RAW_DB.PUBLIC.PRODUCT_SNAPSHOT_SAMPLE s
WHERE t.PRODUCT_ID = s.PRODUCT_ID;

CREATE OR REPLACE TEMPORARY TABLE RAW_DB.PUBLIC.CUSTOMER_SNAPSHOT_SAMPLE AS
SELECT CUSTOMER_ID FROM RAW_DB.PUBLIC.RAW_CUSTOMERS SAMPLE (5000 ROWS);

UPDATE RAW_DB.PUBLIC.RAW_CUSTOMERS t
SET TIER = 'gold', UPDATED_AT = CURRENT_TIMESTAMP()
FROM RAW_DB.PUBLIC.CUSTOMER_SNAPSHOT_SAMPLE s
WHERE t.TIER = 'silver' AND t.CUSTOMER_ID = s.CUSTOMER_ID;

CREATE OR REPLACE TEMPORARY TABLE RAW_DB.PUBLIC.ORDER_SNAPSHOT_SAMPLE AS
SELECT ORDER_ID FROM RAW_DB.PUBLIC.RAW_ORDERS SAMPLE (15000 ROWS);

UPDATE RAW_DB.PUBLIC.RAW_ORDERS t
SET ORDER_STATUS = 'delivered', CREATED_AT = CURRENT_TIMESTAMP()
FROM RAW_DB.PUBLIC.ORDER_SNAPSHOT_SAMPLE s
WHERE t.ORDER_ID = s.ORDER_ID;

SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
