-- ============================================================================
-- Snowflake University: Internals Deep Dive
-- ============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
SET start_ts = CURRENT_TIMESTAMP();
USE DATABASE RAW_DB;

SELECT SYSTEM$CLUSTERING_INFORMATION('RAW_DB.PUBLIC.RAW_ORDERS', '(ORDER_DATE::DATE)') AS cluster_info;
EXECUTE IMMEDIATE $$
BEGIN
  UPDATE RAW_DB.PUBLIC.RAW_ORDERS SET CREATED_AT = CREATED_AT WHERE ORDER_ID IN (SELECT ORDER_ID FROM RAW_DB.PUBLIC.RAW_ORDERS LIMIT 1);
  RETURN 'time_travel_demo_ready';
EXCEPTION
  WHEN STATEMENT_ERROR THEN
    RETURN 'time_travel_demo_skipped: ' || SQLERRM;
END;
$$;
CREATE OR REPLACE DATABASE RAW_DB_DEV CLONE RAW_DB;
EXECUTE IMMEDIATE $$
BEGIN
  CREATE OR REPLACE TABLE RAW_DB.PUBLIC.RAW_ORDERS_YESTERDAY CLONE RAW_DB.PUBLIC.RAW_ORDERS AT(OFFSET => -86400);
  RETURN 'clone_time_travel_ready';
EXCEPTION
  WHEN STATEMENT_ERROR THEN
    CREATE OR REPLACE TABLE RAW_DB.PUBLIC.RAW_ORDERS_YESTERDAY CLONE RAW_DB.PUBLIC.RAW_ORDERS;
    RETURN 'clone_time_travel_fallback_current';
END;
$$;
SELECT COUNT(*), MAX(CREATED_AT) FROM RAW_DB.PUBLIC.RAW_ORDERS_YESTERDAY;
ALTER SESSION SET USE_CACHED_RESULT = FALSE;
SELECT COUNT(*), SUM(AMOUNT) FROM RAW_DB.PUBLIC.RAW_ORDERS WHERE REGION = 'NORTH';
SELECT COUNT(*), SUM(AMOUNT) FROM RAW_DB.PUBLIC.RAW_ORDERS WHERE REGION = 'NORTH';
SELECT QUERY_ID, BYTES_SCANNED, ROWS_PRODUCED, COMPILATION_TIME, EXECUTION_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION()) ORDER BY START_TIME DESC LIMIT 20;
CREATE OR REPLACE RESOURCE MONITOR DEV_MONITOR WITH CREDIT_QUOTA = 100
TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
SELECT DATEDIFF('second', $start_ts, CURRENT_TIMESTAMP()) AS elapsed_seconds;
