-- Refresh all Snowpipes to reload data from S3
ALTER PIPE ANALYTICS.RAW.PIPE_CUSTOMERS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_PRODUCTS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_ORDERS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_ORDER_ITEMS REFRESH;

-- Wait for pipes to process (manual checkpoint - run following queries after a few minutes)

-- Check pipe status and last ingestion
SELECT 
    PIPE_NAME,
    PIPE_OWNER,
    IS_AUTOINGEST_ENABLED,
    LAST_COPIED_FILE_TIMESTAMP,
    NOTIFICATION_CHANNEL_NAME
FROM INFORMATION_SCHEMA.PIPES
WHERE PIPE_SCHEMA = 'RAW'
ORDER BY PIPE_NAME;

-- Check recent copy history for errors
SELECT 
    TABLE_NAME,
    STAGE_LOCATION,
    FILE_NAME,
    STATUS,
    ROW_COUNT,
    ERROR_COUNT,
    LAST_LOAD_TIME
FROM INFORMATION_SCHEMA.COPY_HISTORY
WHERE TABLE_SCHEMA = 'RAW'
  AND LAST_LOAD_TIME >= DATEADD(hour, -24, CURRENT_TIMESTAMP())
ORDER BY LAST_LOAD_TIME DESC
LIMIT 100;

-- Verify data load success by checking row counts
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count, MAX(DMS_LOAD_TS) AS latest_load
FROM ANALYTICS.RAW.CUSTOMERS;

SELECT 'PRODUCTS' AS table_name, COUNT(*) AS row_count, MAX(DMS_LOAD_TS) AS latest_load
FROM ANALYTICS.RAW.PRODUCTS;

SELECT 'ORDERS' AS table_name, COUNT(*) AS row_count, MAX(ORDER_DATE) AS latest_order 
FROM ANALYTICS.ORDERS o
WHERE o.ORDER_DATE >= DATEADD(day, -30, CURRENT_DATE());

SELECT 'ORDER_ITEMS' AS table_name, COUNT(*) AS row_count, MAX(DMS_LOAD_TS) AS latest_load
FROM ANALYTICS.RAW.ORDER_ITEMS;
