-- Refresh all Snowpipes to reload data from S3
ALTER PIPE ANALYTICS.RAW.PIPE_CUSTOMERS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_PRODUCTS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_ORDERS REFRESH;
ALTER PIPE ANALYTICS.RAW.PIPE_ORDER_ITEMS REFRESH;

-- Verify data load success by checking row counts
SELECT 'CUSTOMERS' AS table_name, COUNT(*) AS row_count 
FROM ANALYTICS.RAW.CUSTOMERS;

SELECT 'PRODUCTS' AS table_name, COUNT(*) AS row_count 
FROM ANALYTICS.RAW.PRODUCTS;

SELECT 'ORDERS' AS table_name, COUNT(*) AS row_count, MAX(ORDER_DATE) AS latest_order 
FROM ANALYTICS.ORDERS o
WHERE o.ORDER_DATE >= DATEADD(day, -30, CURRENT_DATE());

SELECT 'ORDER_ITEMS' AS table_name, COUNT(*) AS row_count 
FROM ANALYTICS.RAW.ORDER_ITEMS;
